### ISSUE TITLE
npm run start ERROR in webpack latest version

### ISSUE THREAD

**Issue by CodePsy-2001** [n00begon/phaser-jam-template#123]
sorry for my poor English

![Screenshot_20211230_154909](https://user-images.githubusercontent.com/81800589/147728374-8b29c5c8-a990-4f14-bc21-12eb1c1e3f90.png)

## History
"Use this template" button -> fork -> download on my local computer by using git -> npm install -> npm run start -> ERROR

## Error Message
```
[webpack-cli] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
- options has an unknown property 'contentBase'. These properties are valid:
```

## My Solution
![solution](https://user-images.githubusercontent.com/81800589/147728882-e264f050-48bc-4d9c-8c7d-539a21dbf891.png)
![solution2](https://user-images.githubusercontent.com/81800589/147728887-35e8cf81-cfb6-4a42-bc22-dbae62192a52.png)

and **IT WORKED!**

## Related Article
(https://gist.github.com/johnrichardrinehart/c8ec6ab1e60f39fc3b8dc738db649ec0#gistcomment-3866671)

**Comment by n00begon** [comment]
Awesome thanks for the fix :)
